package com.sahana.feedbacktest;
//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

public class EmpaddTest {
	private WebDriver driver;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void empadd() {
		driver.get("http://localhost:3000/");
		driver.manage().window().setSize(new Dimension(1552, 840));
		driver.findElement(By.linkText("Register employee")).click();
		driver.findElement(By.name("name")).click();
		driver.findElement(By.name("name")).sendKeys("sahana");
		{
			WebElement element = driver.findElement(By.name("desg"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).clickAndHold().perform();
		}
		{
			WebElement element = driver.findElement(By.name("desg"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.name("desg"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).release().perform();
		}
		driver.findElement(By.cssSelector("form")).click();
		driver.findElement(By.name("dept")).sendKeys("cse");
		driver.findElement(By.name("desg")).click();
		driver.findElement(By.name("desg")).sendKeys("professor");
		driver.findElement(By.name("lid")).click();
		{
			WebElement dropdown = driver.findElement(By.name("lid"));
			dropdown.findElement(By.xpath("//option[. = '4']")).click();
		}
		driver.findElement(By.id("submit")).click();
	}
}
