package com.sahana.feedbacktest;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
public class LeaveaddTest {
	private WebDriver driver;
	
	JavascriptExecutor js;

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void leaveadd() {
		driver.get("http://localhost:3000/");
		driver.manage().window().setSize(new Dimension(1552, 840));
		driver.findElement(By.linkText("Register Leave")).click();
		driver.findElement(By.id("ty")).click();
		driver.findElement(By.id("ty")).sendKeys("feverrrrrrrrrrrrrrrrrrrr");
		driver.findElement(By.id("btn-ty")).click();
	}
}
